# Change these first
owner: bonny1992 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Affiliate
    url: $URLS_AFFILIATE
  - name: Bonosaglass.com
    url: $URLS_BGLASS
  - name: Jackett
    url: $URLS_JACKETT
  - name: Ombi
    url: $URLS_OMBI
  - name: Overseerr
    url: $URLS_OVERSEERR
  - name: Deluge
    url: $URLS_DELUGE
  - name: NZBGet
    url: $URLS_NZBGET
  - name: NZBHydra2
    url: $URLS_NZBHYDRA
  - name: Sonarr
    url: $URLS_SONARR
  - name: Radarr
    url: $URLS_RADARR
  - name: Lidarr
    url: $URLS_LIDARR
  - name: PlexPy
    url: $URLS_PLEXPY
  - name: Filebot
    url: $URLS_FILEBOT
    expectedStatusCodes:
      - 401 # As it's behind user+pass
  - name: Synclounge
    url: $URLS_SYNCLOUNGE
  # Will be permanently not working until Cloudbox Community releases a fixed role
  - name: Bazarr
    url: $URLS_BAZARR
  - name: NextCloud
    url: $URLS_NEXTCLOUD

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bonny.pw
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Bonny Status Page
  introTitle: "Bonny Status Page - Powered by Upptime.js"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/bonny1992/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  theme: dark
  assignees:
    - bonny1992
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: More problems? Report it here
      href: https://github.com/$OWNER/$REPO/issues

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
